# src/Louvre/BookingBundle/Resources/config/routing.yml

louvre_booking_homepage1:
    path:     /
    defaults: 
        _controller: LouvreBookingBundle:Booking:index 
        page: 1

louvre_booking_homepage:
    path:     /{page}
    defaults: 
        _controller: LouvreBookingBundle:Booking:index 
    requirements:
        page: \d+

louvre_booking_booking:
    path:    /booking
    defaults:
        _controller: LouvreBookingBundle:Booking:booking  

louvre_booking_checkout:
    path:    /checkout
    defaults: 
        _controller: LouvreBookingBundle:Booking:checkout

louvre_booking_confirmation:
    path:    /confirmation
    defaults: 
        _controller: LouvreBookingBundle:Booking:confirmation  
        
louvre_booking_modify:
    path:    /modify
    defaults:
        _controller: LouvreBookingBundle:Booking:modify

louvre_booking_delete:
    path:    /delete{id}
    defaults: 
        _controller: LouvreBookingBundle:Booking:delete

louvre_booking_informations:
    path:    /informations
    defaults:
        _controller: LouvreBookingBundle:Booking:informations   

louvre_booking_contact:
    path:    /contact
    defaults:
        _controller: LouvreBookingBundle:Booking:contact